### ISSUE TITLE
Address bar is not marked, cursor at start

### ISSUE THREAD

**Issue by testingsw1** [ylor/newtab-home#1]
Windows 10 64bit (21H2 with latest updates)
Firefox 102.0.1
Extension version 1.4

Options
Select preferred cursor location --> Address Bar

Cursor is at beginning of address. Address is not empty nor marked.
Expected behavior is that address is marked (or empty) and we can just start typing new address (now we have to mark it with cursor or press delete multiple times until address is not deleted). Here is the picture (current -> up,red and expected -> below, green, 2 different options):

![image](https://user-images.githubusercontent.com/107328868/180632945-1a51d8a4-ac84-4e8b-bf88-5059110c76e5.png)

@ylor Can you please fix this (and thank you for this great add-on)?

**Comment by ylor** [comment]
@testingsw1 Spend the evening researching and I don't believe Firefox provides a method to focus the address bar with the current contents selected.

Will unfortunately have to close this as wontfix, but it's really more of a cantfix; if you happen to find another similar extension that allows this, please reopen and I'd be glad to dig in deeper.

**Comment by testingsw1** [comment]
Please check this source code (he managed to solve this problem):
https://github.com/ThatCrispyToast/Simple-New-Tab

**Comment by testingsw1** [comment]
[ylor](https://github.com/ylor)
Please check this source code (he managed to solve this problem):
https://github.com/ThatCrispyToast/Simple-New-Tab

**Comment by testingsw1** [comment]
@ylor 

I think you are right... in the end I "solved" it with iframe (entire html is just iframe).
Not pretty, but works :)
