### ISSUE TITLE
Error on opening new tab

### ISSUE THREAD

**Issue by FuryoftheStars** [ylor/newtab-home#2]
Hi, it appears this extension in Firefox just updated today, and now opening new tabs results in an error.
![image](https://github.com/user-attachments/assets/627a9a05-107c-4193-9f9d-effe298a318c)

**Comment by ylor** [comment]
Hi @FuryoftheStars - thank you for the report, I can reproduce. Investigating a solution now.

**Comment by ylor** [comment]
@FuryoftheStars this issue has been resolved with release v1.6.1. Firefox should automatically update automatically but you can force the update by using [these instructions](https://support.mozilla.org/en-US/kb/how-update-add-ons).

**Comment by FuryoftheStars** [comment]
@ylor, thanks, I did have to manually update, but can confirm it is now fixed. :)

**Comment by ylor** [comment]
Apologies for the error and thanks for the report.
